### ISSUE TITLE
NullPointerException for DyamoDB metrics

### ISSUE THREAD

**Issue by nicholasgibson2** [prometheus/cloudwatch_exporter#257]
When the following metrics are configured the exporter throws a NullPointerException.

- AccountProvisionedReadCapacityUtilization
- AccountProvisionedWriteCapacityUtilization
- MaxProvisionedTableReadCapacityUtilization
- MaxProvisionedTableWriteCapacityUtilization

Here is my configuration (I tried each metric individually, all get the same error)
```
---
region: us-west-2
metrics:
  - aws_namespace: AWS/DynamoDB
    aws_metric_name: AccountProvisionedReadCapacityUtilization
    aws_statistics: [Average]
```

Here is the error:
```
WARNING: CloudWatch scrape failed
java.lang.NullPointerException
	at io.prometheus.cloudwatch.CloudWatchCollector.scrape(CloudWatchCollector.java:543)
	at io.prometheus.cloudwatch.CloudWatchCollector.collect(CloudWatchCollector.java:664)
	at io.prometheus.client.CollectorRegistry.collectorNames(CollectorRegistry.java:100)
	at io.prometheus.client.CollectorRegistry.register(CollectorRegistry.java:50)
	at io.prometheus.client.Collector.register(Collector.java:139)
	at io.prometheus.client.Collector.register(Collector.java:132)
	at io.prometheus.cloudwatch.WebServer.main(WebServer.java:27)

2020-03-05 21:39:44.896:INFO::main: Logging initialized @1159ms to org.eclipse.jetty.util.log.StdErrLog
2020-03-05 21:39:44.964:INFO:oejs.Server:main: jetty-9.4.z-SNAPSHOT; built: 2019-02-15T16:53:49.381Z; git: eb70b240169fcf1abbd86af36482d1c49826fa0b; jvm 11.0.6+10
2020-03-05 21:39:45.018:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@4b3c354a{/,null,AVAILABLE}
2020-03-05 21:39:45.044:INFO:oejs.AbstractConnector:main: Started ServerConnector@1992eaf4{HTTP/1.1,[http/1.1]}{0.0.0.0:9106}
2020-03-05 21:39:45.045:INFO:oejs.Server:main: Started @1308ms
Mar 05, 2020 9:39:45 PM io.prometheus.cloudwatch.CloudWatchCollector collect
WARNING: CloudWatch scrape failed
java.lang.NullPointerException
	at io.prometheus.cloudwatch.CloudWatchCollector.scrape(CloudWatchCollector.java:543)
	at io.prometheus.cloudwatch.CloudWatchCollector.collect(CloudWatchCollector.java:664)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:190)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.<init>(CollectorRegistry.java:154)
	at io.prometheus.client.CollectorRegistry.filteredMetricFamilySamples(CollectorRegistry.java:141)
	at io.prometheus.client.exporter.MetricsServlet.doGet(MetricsServlet.java:48)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Unknown Source)
```
I am using the latest docker image, prom/cloudwatch-exporter:latest

**Comment by brian-brazil** [comment]
Looks like we're not handling awsDimensions not being specified. We should default that to the empty list.
