### ISSUE TITLE
NullPointerException -  CloudWatch scrape failed

### ISSUE THREAD

**Issue by devsharma1979** [prometheus/cloudwatch_exporter#304]
Hi Guys,
I am using cloudwatch exporter deployed on Kubernetes cluster (EKS), currently it is configured to poll all the AWS/NetworkELB metrics, some of the metrics are listed below.  Cloudwatch-exporter continuously logs the error message - CloudWatch scrape failed (see stack trace  after the configurations).  
I have posted this at - https://groups.google.com/g/prometheus-users/c/WraLmT04vVk as well.  Can you suggest what could be wrong here ?  

===================== Configuration  ====================

```
region: us-west-2
   metrics:
  - aws_namespace: AWS/NetworkELB
    aws_metric_name: HealthyHostCount
    aws_dimensions: [AvailabilityZone, LoadBalancer, TargetGroup]
    # set_timestamp: true

  - aws_namespace: AWS/NetworkELB
    aws_metric_name: UnHealthyHostCount
    aws_dimensions: [AvailabilityZone, LoadBalancer, TargetGroup]
    # set_timestamp: true

  - aws_namespace: AWS/NetworkELB
    aws_metric_name: TCP_Target_Reset_Count
    aws_dimensions: [AvailabilityZone, LoadBalancer]
```
 

===================== End of  Configuration  ====================  

===================== Stacktrace ====================  

 ```
io.prometheus.cloudwatch.CloudWatchCollector collect
WARNING: CloudWatch scrape failed
java.lang.NullPointerException
        at io.prometheus.cloudwatch.CloudWatchCollector.toSnakeCase(CloudWatchCollector.java:492)
        at io.prometheus.cloudwatch.CloudWatchCollector.scrape(CloudWatchCollector.java:531)
        at io.prometheus.cloudwatch.CloudWatchCollector.collect(CloudWatchCollector.java:664)
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:190)
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:223)
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:144)
        at io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:22)
        at io.prometheus.client.exporter.MetricsServlet.doGet(MetricsServlet.java:48)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:502)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.base/java.lang.Thread.run(Unknown Source)
```

===================== End of Stacktrace ====================

**Comment by brian-brazil** [comment]
What version is this?

**Comment by devsharma1979** [comment]
I am using latest helm chart for deployment - https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-cloudwatch-exporter 
current version is  - cloudwatch_exporter-0.8.0

**Comment by brian-brazil** [comment]
Are you sure that that is exactly the config file being used?

aws_metric_name would need to be null for that stack trace to happen given https://github.com/prometheus/cloudwatch_exporter/blob/cloudwatch_exporter-0.8.0/src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java#L531

**Comment by devsharma1979** [comment]
You are right, I rechecked the configuration and found that metric name is missing for one of the metrics, I looked at this file multiple time and I completely missed it, sorry my bad.  
Thanks for responding so quickly.
