### ISSUE TITLE
Exception in thread "main" java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer

### ISSUE THREAD

**Issue by schnipseljagd** [prometheus/cloudwatch_exporter#4]
I have a config like this:
```json
{
  "region": "eu-west-1",
  "metrics": [
    {"aws_namespace": "AWS/Kinesis", "aws_metric_name": "IncomingRecords",
     "aws_dimensions": ["StreamName"], "aws_statistics": ["Sum"],
     "period_seconds": 300}
  ]
}
```

When starting the exporter it results in:

```
Exception in thread "main" java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
2015-02-24 14:56:05,359 DEBG 'cloudwatchexporter' stderr output:

	at io.prometheus.cloudwatch.CloudWatchCollector.<init>(CloudWatchCollector.java:110)
	at io.prometheus.cloudwatch.CloudWatchCollector.<init>(CloudWatchCollector.java:50)
	at io.prometheus.cloudwatch.WebServer.main(WebServer.java:15)
```

**Comment by brian-brazil** [comment]
Hmm, looking at the docs we should be doing (Number)config.get("period_Seconds")).intValue();
