### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by lijun624-Fred** [prometheus/cloudwatch_exporter#429]
I deployed 10+ containers to collect cloudwatch information for 10+ regions, but only the container for af-south-1 returned error as below:

> ['/opt/home/fuelops/docker-entrypoint.py', 'java', '-jar', '/opt/home/fuelops/cloudwatch_exporter/cloudwatch-exporter.jar', '9122', '/opt/home/fuelops/cloudwatch_exporter/config/cloudwatch_exporter.yml']
> Exception in thread "main" java.lang.NullPointerException
> 	at io.prometheus.cloudwatch.CloudWatchCollector.getMonitoringEndpoint(CloudWatchCollector.java:208)
> 	at io.prometheus.cloudwatch.CloudWatchCollector.loadConfig(CloudWatchCollector.java:134)
> 	at io.prometheus.cloudwatch.CloudWatchCollector.loadConfig(CloudWatchCollector.java:95)
> 	at io.prometheus.cloudwatch.CloudWatchCollector.<init>(CloudWatchCollector.java:73)

The yaml is: (use the same yaml setup for other regions..)

> cloudwatch-exporter-af-south-1:
>     Container ID:  docker://275f6f03af6e06ecac66b53751b6d870609d4d3be1841e0fe9ee063641fb5470
>     Image:         263777168895.dkr.ecr.us-east-1.amazonaws.com/fuelops-cloudwatch-exporter:0.3.3-0.5.0
>     Image ID:      docker-pullable://263777168895.dkr.ecr.us-east-1.amazonaws.com/fuelops-cloudwatch-exporter@sha256:da24d1b781c2532402e481d1d25f584052ee279522a44ce53256296f27065e8c
>     Port:          9122/TCP
>     Host Port:     9122/TCP
>     Args:
>       java
>       -jar
>       /opt/home/fuelops/cloudwatch_exporter/cloudwatch-exporter.jar
>       9122
>       /opt/home/fuelops/cloudwatch_exporter/config/cloudwatch_exporter.yml
>     State:          Waiting
>       Reason:       CrashLoopBackOff
>     Ready:          False
>     Restart Count:  7
>     Liveness:       http-get http://:9122/-/healthy delay=15s timeout= 10s period=10s #success=1 #failure=3
>     Readiness:      http-get http://:9122/-/ready delay=5s timeout=5s period=10s #success=1 #failure=3
>     Environment:
>       AWS_REGION:      af-south-1
>       INSTANCE_ROLE:   prom
>       TITLE_RELEASE:   fm22
>       TITLE_PREFIX:    fm
>       SERVICE_ENV:     test
>       NETWORK_ENV:     test
>       CONTAINER_NAME:  cloudwatch-exporter-af-south-1
>       NAMESPACE:       default
>     Mounts:
>       /opt/home/fuelops/cloudwatch_exporter_template/config from cloudwatch-exporter-config (rw)
>       /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-wbkl5 (ro)

Did I miss anything or cloudwatch_exporter doesn't support af-south-1 region.

**Comment by lijun624-Fred** [comment]
resolved by using the latest release
