### ISSUE TITLE
CloudWatch scrape failed cannot be cast to java.util.List

### ISSUE THREAD

**Issue by sthammana** [prometheus/cloudwatch_exporter#46]
Dec 22, 2016 8:39:36 PM io.prometheus.cloudwatch.CloudWatchCollector collect
WARNING: CloudWatch scrape failed
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at io.prometheus.cloudwatch.CloudWatchCollector.metricIsInAwsDimensionSelectRegex(CloudWatchCollector.java:240)
	at io.prometheus.cloudwatch.CloudWatchCollector.useMetric(CloudWatchCollector.java:207)
	at io.prometheus.cloudwatch.CloudWatchCollector.getDimensions(CloudWatchCollector.java:187)
	at io.prometheus.cloudwatch.CloudWatchCollector.scrape(CloudWatchCollector.java:312)
	at io.prometheus.cloudwatch.CloudWatchCollector.collect(CloudWatchCollector.java:377)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:73)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.<init>(CollectorRegistry.java:65)
	at io.prometheus.client.CollectorRegistry.metricFamilySamples(CollectorRegistry.java:56)
	at io.prometheus.client.exporter.MetricsServlet.doGet(MetricsServlet.java:41)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)

**Comment by brian-brazil** [comment]
The code looks okay to me. Can you confirm you're on the latest version?

**Comment by sthammana** [comment]
yes i'm on the latest, it was my env var problem. now I don't see this issue
