### ISSUE TITLE
Scraping stops working from time to time

### ISSUE THREAD

**Issue by ivanfoo** [prometheus/cloudwatch_exporter#74]
We have deployed the last version of the cloudwatch-exporter. We noticed that it stops getting logs from AWS sometimes and never recovers, having to restart it to fix it. What could be the cause? Maybe the size of the response? I included some logs below:

```
WARNING: CloudWatch scrape failed
Message: Read timed out). Response Code: 200, Response Text: OK
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleResponse(AmazonHttpClient.java:1525)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1035)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:721)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:672)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:654)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:518)
	at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.doInvoke(AmazonCloudWatchClient.java:965)
	at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.listMetrics(AmazonCloudWatchClient.java:684)
	at io.prometheus.cloudwatch.CloudWatchCollector.getDimensions(CloudWatchCollector.java:188)
	at io.prometheus.cloudwatch.CloudWatchCollector.scrape(CloudWatchCollector.java:329)
	at java.util.Collections.list(Collections.java:3688)
	at io.prometheus.client.exporter.MetricsServlet.doGet(MetricsServlet.java:40)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:365)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:926)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:988)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:635)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:51)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:599)
	at com.amazonaws.transform.StaxUnmarshallerContext.nextEvent(StaxUnmarshallerContext.java:220)
com.amazonaws.SdkClientException: Unable to unmarshall response (ParseError at [row,col]:[1039,14]
	at com.amazonaws.services.cloudwatch.model.transform.ListMetricsResultStaxUnmarshaller.unmarshall(ListMetricsResultStaxUnmarshaller.java:30)
	at com.amazonaws.http.StaxResponseHandler.handle(StaxResponseHandler.java:101)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleResponse(AmazonHttpClient.java:1501)
	... 41 more
Sep 24, 2017 1:45:24 AM io.prometheus.cloudwatch.CloudWatchCollector collect
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1222)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:747)
	at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.invoke(AmazonCloudWatchClient.java:941)
	at io.prometheus.cloudwatch.CloudWatchCollector.collect(CloudWatchCollector.java:410)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:143)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:158)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:128)
	at io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:22)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:648)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:627)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1039,14]
Message: Read timed out
	at com.sun.xml.internal.stream.XMLEventReaderImpl.peek(XMLEventReaderImpl.java:275)
	at com.amazonaws.services.cloudwatch.model.transform.DimensionStaxUnmarshaller.unmarshall(DimensionStaxUnmarshaller.java:40)
	at com.amazonaws.services.cloudwatch.model.transform.ListMetricsResultStaxUnmarshaller.unmarshall(ListMetricsResultStaxUnmarshaller.java:54)
	at com.amazonaws.http.StaxResponseHandler.handle(StaxResponseHandler.java:43)
	at com.amazonaws.http.response.AwsResponseHandlerAdapter.handle(AwsResponseHandlerAdapter.java:70)
``` 
Thanks!

**Comment by brian-brazil** [comment]
That's a timeout from Cloudwatch, nothing we can do about it.

**Comment by ivanfoo** [comment]
But why does the exporter never work again? I understand that it can be a timeout from CloudWatch, but not _forever_

**Comment by brian-brazil** [comment]
That sounds like a network problem.

**Comment by ivanfoo** [comment]
Definitely, I'll recheck in our side. Thanks :+1:

**Comment by ivanfoo** [comment]
It failed last Friday again... The network was working fine and all the other services too @brian-brazil

**Comment by brian-brazil** [comment]
A read timeout is almost certainly an issue with either the network or cloudwatch.

**Comment by ivanfoo** [comment]
I can perform queries against cloudwatch from the instance without issues and the network is working fine. As the previous time, the exporter failed at some point and never recovered, being 3 days out of service

**Comment by brian-brazil** [comment]
Can you provide more debugging information? There's nothing in the code that can get stuck.

**Comment by ivanfoo** [comment]
@brian-brazil sorry I didn't answer before. Yesterday, we found out a strange behaviour that could be related with this. We performed some changes so we will wait some time to see how it works.

Thanks!

**Comment by dene14** [comment]
Hi @ivanfoo !
Can you share your findings? Facing quite the same issue since recently. Configuration hasn't been changed on our end.

**Comment by brian-brazil** [comment]
There's still not enough evidence to say this is a problem in the cloudwatch exporter, this still looks like an issue elsewhere.

**Comment by iyesin** [comment]
@brian-brazil I'm sorry, I thought we are talking about IT. "Somewhere else" looks like "works on my computer" in this situation. I described you my situation, symptoms, temporary solution. [Here](https://github.com/iyesin/cloudwatch_exporter/commit/f7cbb78183dfe8efb531b2ae59bc50ad4440690e) is changes I made to exporter (some of them is overkill I know). This fixed `cloudwatch_exporter`'s non-replying behavior and allowed to trigger error earlier. What evidence what do you need?

**Comment by brian-brazil** [comment]
A plausible mechanism would be useful, for example given `setUseTcpKeepAlive` is part of the things your tried this could be your network breaking TCP but there's not enough information here to indicate what the problem is.

**Comment by iyesin** [comment]
Wow-wow-wow… my `cloud_exporter` is running on AWS. Are you going to argue about AWS network reliability? `TcpKeepAlive` was an attempt to maximize amount of data, we are receiving before `scrape_timeout` fires. I can drop it and retry. I'm ready to bet this will change nothing in current picture.
Even with non-reliable network it is not very good idea to stop replying instead of doing graceful degradation. Please, take a look to defaults of `ClientConfiguration` and then you can imagine, why `cloudwatch_exporter` can fail in situation I described above.

**Comment by brian-brazil** [comment]
That's not what this issue is about, the claim is that the cloudwatch exporter breaks and does not recover. This was determined by the original reporter to be an issue on their machine.

**Comment by iyesin** [comment]
Ok then. I will open new issue with almost same content.
