### ISSUE TITLE
Scraping stops working untill restart

### ISSUE THREAD

**Issue by iyesin** [prometheus/cloudwatch_exporter#86]
Here is my investigation.

First of all, I want to describe my situation:
1. My company's setup has a lots of metrics in `CloudWatch`
1. `cloudwatch_exporter` was failing from time to time. Sometimes it was after one day, sometime after 1 hour after restart. Symptoms — it prints same backtrace below and then stops to reply to `prometheus`. This was annoying and painful for ops team (meaningless alerts, you know)
1. I did dirty patch to `cloudwatch_exporter` ([here it is](https://github.com/iyesin/cloudwatch_exporter/commit/f7cbb78183dfe8efb531b2ae59bc50ad4440690e)) to hardcode execution/connection/request timeouts (via supplying `ClientConfiguration` to `AmazonCloudWatchClient`). Values, I specified there is lower than prometheus' `scrape_timeout`
1. `cloudwatch_exporter` still printing backtraces (mostly about empty XML document), but it is continue running and replying.
1. My suggestion is to add ability to specify ClientConfiguration parameters (at least timeouts) via config file.
1. Here is backtrace:
```
WARNING: CloudWatch scrape failed
com.amazonaws.SdkClientException: Unable to unmarshall response (java.net.SocketTimeoutException: Read timed out). Response Code: 200, Response Text: OK
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleResponse(AmazonHttpClient.java:1525)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1222)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1035)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:747)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:721)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:704)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:672)
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:654)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:518)
at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.doInvoke(AmazonCloudWatchClient.java:965)
at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.invoke(AmazonCloudWatchClient.java:941)
at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.listMetrics(AmazonCloudWatchClient.java:684)
at io.prometheus.cloudwatch.CloudWatchCollector.getDimensions(CloudWatchCollector.java:188)
at io.prometheus.cloudwatch.CloudWatchCollector.scrape(CloudWatchCollector.java:329)
at io.prometheus.cloudwatch.CloudWatchCollector.collect(CloudWatchCollector.java:410)
at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:143)
at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:158)
at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:128)
at java.util.Collections.list(Collections.java:3688)
at io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:22)
at io.prometheus.client.exporter.MetricsServlet.doGet(MetricsServlet.java:40)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:648)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
at org.eclipse.jetty.server.Server.handle(Server.java:365)
at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485)
at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:926)
at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:988)
at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:635)
at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:627)
at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:51)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
at java.lang.Thread.run(Thread.java:745)
Caused by: javax.xml.stream.XMLStreamException: java.net.SocketTimeoutException: Read timed out
at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.setInputSource(XMLStreamReaderImpl.java:212)
at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.<init>(XMLStreamReaderImpl.java:184)
at com.sun.xml.internal.stream.XMLInputFactoryImpl.getXMLStreamReaderImpl(XMLInputFactoryImpl.java:277)
at com.sun.xml.internal.stream.XMLInputFactoryImpl.createXMLStreamReader(XMLInputFactoryImpl.java:129)
at com.sun.xml.internal.stream.XMLInputFactoryImpl.createXMLEventReader(XMLInputFactoryImpl.java:78)
at com.amazonaws.http.StaxResponseHandler.handle(StaxResponseHandler.java:91)
at com.amazonaws.http.StaxResponseHandler.handle(StaxResponseHandler.java:43)
at com.amazonaws.http.response.AwsResponseHandlerAdapter.handle(AwsResponseHandlerAdapter.java:70)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleResponse(AmazonHttpClient.java:1501)
... 41 more
Caused by: java.net.SocketTimeoutException: Read timed out
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.read(SocketInputStream.java:153)
at java.net.SocketInputStream.read(SocketInputStream.java:122)
at sun.security.ssl.InputRecord.readFully(InputRecord.java:442)
at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:554)
at sun.security.ssl.InputRecord.read(InputRecord.java:509)
at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:944)
at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:901)
at sun.security.ssl.AppInputStream.read(AppInputStream.java:102)
at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:178)
at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:139)
at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:120)
at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:66)
at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:158)
at com.sun.org.apache.xerces.internal.impl.XMLEntityManager$RewindableInputStream.read(XMLEntityManager.java:2898)
at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:673)
at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(XMLEntityManager.java:1304)
at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startDocumentEntity(XMLEntityManager.java:1255)
at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.setInputSource(XMLDocumentScannerImpl.java:257)
at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.setInputSource(XMLStreamReaderImpl.java:199)

... 49 more```

**Comment by brian-brazil** [comment]
Can you clarify what you mean by "then stops to reply to prometheus"? This looks like a problem on Cloudwatch's end.

**Comment by iyesin** [comment]
@brian-brazil of course. This means `cloudwatch_exporter` accepting connection, but gives no a reply to prometheus during `scrape_timeout` interval. Restarting container with `cloudwatch_exporter` solves this issue. Applying patch I mentioned above - also solves a problem, but with price of partial monitoring data loss. For my company it's completely ok to loose some of monitoring data, but not receive false alarms.

**Comment by brian-brazil** [comment]
Is the cloudwatch overloaded somehow when this happens? It doesn't sound like a FD leak, could be CPU.

**Comment by iyesin** [comment]
@brian-brazil this exporter is running inside separate container with guarantied amount of CPU time (at least one core of r4.4xlarge). There was no CPU usage spikes (as now also), and server have enough free resources.

**Comment by brian-brazil** [comment]
Was there anything weird happening to other processes on the machine? Do you have an strace or other debug information about the cloudwatch exporter in this state?

**Comment by iyesin** [comment]
@brian-brazil 
- There was nothing weird happening on this machine (container have guaranteed resources, no swapping, no CPU or RAM hungry tasks on same machine)
- No, I don't have debug information about terminal state (it is production environment)
- Even without compression and keepalives (tcp and http) patched version works ok for 12 hours

**Comment by brian-brazil** [comment]
Can you obtain debug information please?

**Comment by iyesin** [comment]
@brian-brazil how do you prefer this should be done? If possible, step-by-step instruction convenient for long-running tasks.

**Comment by christoph-buente** [comment]
Hey @brian-brazil, how can we obtain the information you need from our exporter? Is it simply switching logs to debug level? Or is there any special java flag to use? Please help us to help you. Thanks

**Comment by brian-brazil** [comment]
I'd suggest starting with strace to see what's going on.

**Comment by iyesin** [comment]
@brian-brazil https://s3.amazonaws.com/liveintent-ilya-test/pub/cloudwatch_exporter.log.xz
Please, let me know, when I can delete this file

**Comment by brian-brazil** [comment]
At what time did the failures start in that file?

**Comment by iyesin** [comment]
@brian-brazil 
At the end of file. This is side-effect of running exporter with strace - it failing instead of hanging. Furthermore after enabling strace, exporter became much slower and CPU hungry. Any other options to trace/debug this?

**Comment by brian-brazil** [comment]
What exact time? This is a 8GB file, it's not exactly easy to work with.

**Comment by brian-brazil** [comment]
You also didn't mention that you are using an AWS ALB, details like this are important. Try scraping the cloudwatch exporter directly.

**Comment by brian-brazil** [comment]
It looks like something is not following POSIX, the kernel is returning EPIPE on a sendto for a connection which was not closed on the local side. This sounds like a kernel bug.

**Comment by iyesin** [comment]
@brian-brazil 

> You also didn't mention that you are using an AWS ALB, details like this are important.

Are you sure? Timeouts on ALB is twice higher that scrape_timeout.

>  Try scraping the cloudwatch exporter directly.

I will try soon. Without containers and without strace (it's way too slow)

> the kernel is returning EPIPE on a sendto for a connection which was not closed on the local side. This sounds like a kernel bug

The source of that, most likely, is how ECS logger works with this amount of data

Furthermore, I'm pretty sure, it is not good idea to strace long-running java applications because:
- size of logs
- meaningful amount of data (signal-to-noice ratio is very low)
- application changes it's behavior running under strace: execution flow became linear (non-parallel), ptrace(2) overhead, execution flow slowdown due output slowdown
- linear execution flow can hide race-conditions

Because of things above, please let me know, if there any way (except gdb) to debug exporter in it's terminal state.

**Comment by brian-brazil** [comment]
> Are you sure? Timeouts on ALB is twice higher that scrape_timeout.

When trying to debug a weird problem, every detail matters.

Strace may slow things down, but it should not affect behaviour in a case like this. As this looks like a syscall level issue, strace is the appropriate tool. You can attach strace on the fly.

**Comment by iyesin** [comment]
@brian-brazil I got your point. Today I will spin up new instance for this purposes.

**Comment by iyesin** [comment]
@brian-brazil progress report. 8 days under strace on bare ec2 instance up and running. No hangups. Going to add ALB on top of it.

**Comment by brian-brazil** [comment]
Is this still happening in the simple setup?

**Comment by iyesin** [comment]
Nope. I can't reproduce this situation anymore in ec2 instance. I will reopen ticket after migrating exporter to ECS.
