### ISSUE TITLE
Unable to load AWS credentials from any provider in the chain

### ISSUE THREAD

**Issue by avendretter** [prometheus/cloudwatch_exporter#88]
Hey @ all,

I just started working on a monitoring project in my company. I need to include AWS-Cloudwatch.

So Prometheus is up and running. I now want to include AWS-Cloudwatch metrics.
But as soon as I launched the docker-container this error message appears:

```
Feb 13, 2018 10:14:28 AM io.prometheus.cloudwatch.CloudWatchCollector collect
WARNING: CloudWatch scrape failed
com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain
	at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:131)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1115)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:764)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:728)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:721)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:672)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:654)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:518)
	at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.doInvoke(AmazonCloudWatchClient.java:965)
	at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.invoke(AmazonCloudWatchClient.java:941)
	at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.getMetricStatistics(AmazonCloudWatchClient.java:630)
	at io.prometheus.cloudwatch.CloudWatchCollector.scrape(CloudWatchCollector.java:365)
	at io.prometheus.cloudwatch.CloudWatchCollector.collect(CloudWatchCollector.java:443)
	at io.prometheus.client.CollectorRegistry.collectorNames(CollectorRegistry.java:99)
	at io.prometheus.client.CollectorRegistry.register(CollectorRegistry.java:50)
	at io.prometheus.client.Collector.register(Collector.java:128)
	at io.prometheus.client.Collector.register(Collector.java:121)
	at io.prometheus.cloudwatch.WebServer.main(WebServer.java:25)

2018-02-13 10:14:28.729:INFO:oejs.Server:jetty-8.y.z-SNAPSHOT
2018-02-13 10:14:28.795:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:9106
```

My Acces key ID and Secret access key are set in .bash_profile and in .aws/credentials
I double checked that.

I looked quite a while on the internet for a solution, but nothing worked for me :/ 
Some suggestions?

BTW my config file looks like this, just for testing:
```
---
region: us-east-1
metrics:
- aws_namespace: AWS/ApplicationELB
  aws_metric_name: UnHealthyHostCount

- aws_namespace: AWS/ApplicationELB
  aws_metric_name: HealthyHostCount
```

and also my IAM settings for Cloudwatch:
![screen shot 2018-02-13 at 11 31 25](https://user-images.githubusercontent.com/1587171/36145401-8974173a-10b1-11e8-9d52-c956790e4fe4.png)

Best,
Avendretter

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
